# environment variables
## DEFAULT Shell
export SHELL=/usr/bin/zsh
## Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
## Set language environment
export LANG=en_US.UTF-8

# Aliases
alias vim="nvim"

# Set name of the theme to load
ZSH_THEME="spaceship"

# Time zone
TZ='Asia/Seoul'

# Specify the plugins to use
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    direnv
)

source $ZSH/oh-my-zsh.sh

# Functions
function switch_cuda {
  v=$1
  sudo ln -sfT /usr/local/cuda-$v/ /usr/local/cuda
  nvcc --version
}
